/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package xiangqi;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author OMy
 */
public class Global extends javax.swing.JPanel {

    /**
     * Creates new form Global
     */
    
    User opp;
    private CardLayout cardlayout;
    private JPanel cardpanel;
    
    public Global(CardLayout cardlayout, JPanel cardpanel, User vsuser) {
    this.cardlayout = cardlayout;
    this.cardpanel = cardpanel;
    initComponents();  // Inicializa los componentes

    if (vsuser != null) {
        username.setText(vsuser.getUsername());  // Establece el nombre de usuario después de inicializar
    }
    opp=vsuser;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        versus = new javax.swing.JButton();
        username = new javax.swing.JLabel();

        versus.setText("Play");
        versus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                versusActionPerformed(evt);
            }
        });

        username.setText("Omar Romero");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(versus, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(versus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void versusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_versusActionPerformed
        // TODO add your handling code here:
        XiangqiGame xiangqiGame = new XiangqiGame(cardlayout, cardpanel, opp);
        cardpanel.add(xiangqiGame, "game");
        cardlayout.show(cardpanel, "game"); 
    }//GEN-LAST:event_versusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel username;
    private javax.swing.JButton versus;
    // End of variables declaration//GEN-END:variables
}
